name: Jupyter notebooks

on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test notebooks are runnable and up-to-date
    steps:
    - name: Test 1
      id: test1
      uses: docker://ebmdatalab/datalab-jupyter:python3.8.1
      with:
        args: 'ls -l'
    - name: Test
      id: test2
      uses: docker://ebmdatalab/datalab-jupyter:python3.8.1
      with:
        args: 'py.test --nbval notebooks'
